### ISSUE TITLE
Cannot find the right printer

### ISSUE THREAD

**Issue by b2renger** [gohai/processing-simplereceiptprinter#1]
Hello @gohai 

Thank you for the library  that looks awesome although I have some trouble making it work so I have a few questions  : 

- First is this library only supposed to work with arduino, or could I use a FTDI and try to run from a classic version of processing. (I've tried it but I couldn't find the printer in the serial list), maybe I just don't have the 'right' FTDI adapter ?

- On raspberry I've tried to make this kind of connection
https://cdn-blog.adafruit.com/uploads/2012/11/RaspPiThermal_patch.png

I also have tried all the listed  devices from the list in the console with no luck.

The last thing that I see is passing the firmware version, but my printer in the test print writes "1.00.78 NVT", so I tried passing it "1.78" but again with no luck.

I'm using the latest version of processing for the rpi (3.5.4), on a rpi3 model b.

Is there other things I could try to make it work ?

**Comment by gohai** [comment]
Hello @b2renger

This library was made for, and tested with, only the Raspberry Pi running Processing. Looking at its source code (it has been a while), I don't see no fundamental reason why it shouldn't work on on "classic" Processing as well - I just wouldn't be surprised if the output quality won't be that great, because the library needs to do quite a bit of precise sleeping as to send data to the printer at exactly the right time, and USB would definitely add some jitter there. You should always see the FTDI (or similar) adapter's port in `list()`, since this just returns the ports Processing's serial library sees. So if you aren't I would check if the FTDI port indeed shows up elsewhere (e.g. in the Device Manger), and if it possibly needs some drivers.

On the Pi: the connections look good. Have you enabled the Serial interface in the Raspberry Pi configuration? (e.g. `raspi-config`) Since you're using the Pi 3: Try using [this preconfigured Raspbian Remix](https://pi.processing.org/download/), which has all the necessary configuration done, and I believe the SimpleReceiptPrinter is preinstalled there as well.

If you want to use Arduino instead, I'd recommend [this library](https://github.com/adafruit/Adafruit-Thermal-Printer-Library) by Adafruit, which mine is based on.

BTW: If you're looking for a robust rather than a cheap solution, I have heard really good things about the Epson TM-T88V printer. If I would have some use for one in the future, I would likely get this one, or a similar USB-connected one, for which a proper CUPS driver exits. (Less headache, more compatibility with random programs.)

**Comment by b2renger** [comment]
Thanks a lot for your feedback !
 I will investigate following your suggestions and get back to you to let you know how it went

**Comment by b2renger** [comment]
Hello

Indeed enabling the Serial interface does the trick for the rpi. Thanks for that. 

No luck with the FTDI yet though.

Do you want me to eventually send you a PR, when my research is done, to add a readme with a little documentation ? (schematics / raspi-config and maybe ftdi if I manage to get this to work and maybe some examples )

**Comment by gohai** [comment]
@b2renger Great to hear. FTDI / documentation: happy to have a look at a PR, but at the moment I don't have plans to develop this library further, so whatever you prefer. Thanks!

**Comment by b2renger** [comment]
Ok great thanks for your help ! I'll ping you through a PR if I manage to get something interesting done.
And thanks for the great lib, it's really great to be able to use a thermal printer with processing code :)
